# Organizing 2022-2023

## Formatting Begin

In [198]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('2022-2023.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 41 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   55 non-null     object
 1   First        51 non-null     object
 2   Unnamed: 2   53 non-null     object
 3   Unnamed: 3   51 non-null     object
 4   Unnamed: 4   47 non-null     object
 5   Unnamed: 5   47 non-null     object
 6   Unnamed: 6   9 non-null      object
 7   Unnamed: 7   9 non-null      object
 8   Unnamed: 8   9 non-null      object
 9   Second       47 non-null     object
 10  Unnamed: 10  51 non-null     object
 11  Unnamed: 11  53 non-null     object
 12  Unnamed: 12  53 non-null     object
 13  Unnamed: 13  47 non-null     object
 14  Unnamed: 14  47 non-null     object
 15  Unnamed: 15  42 non-null     object
 16  Unnamed: 16  47 non-null     object
 17  Third        42 non-null     object
 18  Unnamed: 18  53 non-null     object
 19  Unnamed: 19  55 non-null     object
 20  Unnamed: 20  49 non-null     object
 21  Unnamed: 21  43 non-null     object
 22  Unnamed: 22  9 non-null      object
 23  Unnamed: 23  9 non-null      object
 24  Unnamed: 24  9 non-null      object
 25  Fourth       51 non-null     object
 26  Unnamed: 26  42 non-null     object
 27  Unnamed: 27  55 non-null     object
 28  Unnamed: 28  51 non-null     object
 29  Unnamed: 29  49 non-null     object
 30  Unnamed: 30  45 non-null     object
 31  Unnamed: 31  51 non-null     object
 32  Unnamed: 32  55 non-null     object
 33  Fifth        55 non-null     object
 34  Unnamed: 34  45 non-null     object
 35  Unnamed: 35  55 non-null     object
 36  Unnamed: 36  45 non-null     object
 37  Unnamed: 37  49 non-null     object
 38  Unnamed: 38  55 non-null     object
 39  Unnamed: 39  9 non-null      object
 40  Unnamed: 40  9 non-null      object
dtypes: object(41)
memory usage: 20.9+ KB

,Unnamed: 0,First,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second,...,Unnamed: 31,Unnamed: 32,Fifth,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
count,55,51,53,51,47,47,9,9,9,47,...,51,55,55,45,55,45,49,55,9,9
unique,15,30,41,38,26,26,1,1,1,27,...,36,44,45,22,39,21,31,44,1,1
top,Total Load,Week 1,Week 2,Week 3,0,0,Week 6,Week 7,Week 8,0,...,Week 7,Week 8,Week 1,0,Week 3,0,Week 5,Week 6,Week 7,Week 8
freq,9,9,9,9,12,12,9,9,9,12,...,9,9,9,15,9,15,9,9,9,9

In [199]:
df.head()

,Unnamed: 0,First,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second,...,Unnamed: 31,Unnamed: 32,Fifth,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,Chest,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,Total Load,0,"8,690","6,085","2,360","7,300",NaN,NaN,NaN,"7,915",...,"10,520","12,434","12,075",0,"15,804","13,600",0,"16,595",NaN,NaN
2,Total Sets,0,15,14,8,13,NaN,NaN,NaN,12,...,19,21,23,0,24,20,0,27,NaN,NaN
3,Total Reps,0,141,136,88,129,NaN,NaN,NaN,125,...,235,237,259,0,264,255,0,373,NaN,NaN
4,Weights Per Rep,NaN,62,45,27,57,NaN,NaN,NaN,63,...,45,52,47,NaN,60,53,NaN,44,NaN,NaN

In [200]:
df.shape

(65, 41)

In [201]:
list(df.columns) #identifying columns needed for renaming

['Unnamed: 0',
 'First',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Second',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Third',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Fourth',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Fifth',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40']

In [202]:
df.iloc[:, 1:41]

,First,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second,Unnamed: 10,...,Unnamed: 31,Unnamed: 32,Fifth,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,Week 2,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,0,"8,690","6,085","2,360","7,300",NaN,NaN,NaN,"7,915","10,441",...,"10,520","12,434","12,075",0,"15,804","13,600",0,"16,595",NaN,NaN
2,0,15,14,8,13,NaN,NaN,NaN,12,13,...,19,21,23,0,24,20,0,27,NaN,NaN
3,0,141,136,88,129,NaN,NaN,NaN,125,121,...,235,237,259,0,264,255,0,373,NaN,NaN
4,NaN,62,45,27,57,NaN,NaN,NaN,63,86,...,45,52,47,NaN,60,53,NaN,44,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,148,99,50,NaN,NaN,NaN,NaN,NaN,120,140,...,NaN,157,207,NaN,207,NaN,NaN,108,NaN,NaN
61,0%,-49%,-98%,NaN,NaN,NaN,NaN,NaN,58%,14%,...,NaN,3%,24%,NaN,0%,NaN,NaN,-92%,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,June 28-July 1,July 5-9,July 18-21,July 25-26,Aug 8-9,NaN,NaN,NaN,Oct 13-14,Oct 17-21,...,July 3-8,July 10-14,July 17-21,July 24-25,July 31-Aug 4,Aug 7-11,Aug 14-18,Aug 21-26,NaN,NaN

In [203]:
#Changing the Columns to better identify weeks and sections(Week 1.1 is First Grouping First Week)
df1 = df.rename(columns={'Unnamed: 0': "2022-2023",
 'First': "Week 1.1",
 'Unnamed: 2': "Week 1.2",
 'Unnamed: 3': "Week 1.3",
 'Unnamed: 4': "Week 1.4",
 'Unnamed: 5': "Week 1.5",
 'Unnamed: 6': "Week 1.6",
 'Unnamed: 7': "Week 1.7",
 'Unnamed: 8': "Week 1.8",
 'Second': "Week 2.1",
 'Unnamed: 10': "Week 2.2",
 'Unnamed: 11': "Week 2.3",
 'Unnamed: 12': "Week 2.4",
 'Unnamed: 13': "Week 2.5",
 'Unnamed: 14': "Week 2.6",
 'Unnamed: 15': "Week 2.7",
 'Unnamed: 16': "Week 2.8",
 'Third': "Week 3.1",
 'Unnamed: 18': "Week 3.2",
 'Unnamed: 19': "Week 3.3",
 'Unnamed: 20': "Week 3.4",
 'Unnamed: 21': "Week 3.5",
 'Unnamed: 22': "Week 3.6",
 'Unnamed: 23': "Week 3.7",
 'Unnamed: 24': "Week 3.8",
 'Fourth': "Week 4.1",
 'Unnamed: 26': "Week 4.2",
 'Unnamed: 27': "Week 4.3",
 'Unnamed: 28': "Week 4.4",
 'Unnamed: 29': "Week 4.5",
 'Unnamed: 30': "Week 4.6",
 'Unnamed: 31': "Week 4.7",
 'Unnamed: 32': "Week 4.8",
 'Fifth': "Week 5.1",
 'Unnamed: 34': "Week 5.2",
 'Unnamed: 35': "Week 5.3",
 'Unnamed: 36': "Week 5.4",
 'Unnamed: 37': "Week 5.5",
 'Unnamed: 38': "Week 5.6",
 'Unnamed: 39': "Week 5.7",
 'Unnamed: 40': "Week 5.8" }, inplace=True)

In [204]:
print(df.columns) #verification of rename

Index(['2022-2023', 'Week 1.1', 'Week 1.2', 'Week 1.3', 'Week 1.4', 'Week 1.5',
       'Week 1.6', 'Week 1.7', 'Week 1.8', 'Week 2.1', 'Week 2.2', 'Week 2.3',
       'Week 2.4', 'Week 2.5', 'Week 2.6', 'Week 2.7', 'Week 2.8', 'Week 3.1',
       'Week 3.2', 'Week 3.3', 'Week 3.4', 'Week 3.5', 'Week 3.6', 'Week 3.7',
       'Week 3.8', 'Week 4.1', 'Week 4.2', 'Week 4.3', 'Week 4.4', 'Week 4.5',
       'Week 4.6', 'Week 4.7', 'Week 4.8', 'Week 5.1', 'Week 5.2', 'Week 5.3',
       'Week 5.4', 'Week 5.5', 'Week 5.6', 'Week 5.7', 'Week 5.8'],
      dtype='object')

In [205]:
#establishes new identifiers for table to begin creating multiple tables for refrence
col0 = df.iloc[:, 0]
metric_names = ['Total Load', 'Total Sets', 'Total Reps', 'Weights Per Rep']
muscles = col0[~col0.isna() & ~col0.str.strip().isin(metric_names)].str.strip().tolist()

## Total Load

In [279]:
#begin total load table
muscles = ["Chest","Shoulders", "Triceps", "Upper Back", "Traps", "Biceps", "Quads", "Hamstrings", "Calves"] #mucle groups
weeks = df.columns[1:] #column 0 is for the year and weeks, so begining on column 1
total_load_table = pd.DataFrame(index=weeks, columns=muscles)
print(total_load_row.shape)

(40,)

In [280]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df)
  muscle_block = df.iloc[muscle_idx+1 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Total Load"
  total_load_row = muscle_block[mask].iloc[0, 1:]
  total_load_table[muscle] = total_load_row.values.flatten()

In [261]:
total_load_table.to_csv('total_load_table.csv', index=False)
from google.colab import files
files.download('total_load_table.csv')

In [290]:
#verification of new table total load and beggining of cleaning of data
df_1 = pd.read_csv('total_load_table.csv')
df_1 = df_1.apply(lambda x: pd.to_numeric(x.astype(str).str.replace(',', '').str.strip(), errors='coerce'))
df_1.info()
df_1.describe()
df_1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chest       31 non-null     float64
 1   Shoulders   32 non-null     float64
 2   Triceps     32 non-null     float64
 3   Upper Back  32 non-null     float64
 4   Traps       32 non-null     float64
 5   Biceps      32 non-null     float64
 6   Quads       32 non-null     float64
 7   Hamstrings  32 non-null     float64
 8   Calves      32 non-null     float64
dtypes: float64(9)
memory usage: 2.9 KB

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,0.0,720.0,6088.0,5008.0,0.0,4280.0,14830.0,9825.0,8850.0
1,8690.0,390.0,6036.0,10235.0,0.0,4830.0,20030.0,10350.0,3450.0
2,6085.0,0.0,7275.0,2400.0,0.0,4590.0,10800.0,12120.0,3000.0
3,2360.0,1560.0,0.0,3840.0,0.0,0.0,12100.0,11820.0,0.0
4,7300.0,1440.0,0.0,4080.0,0.0,0.0,5300.0,4500.0,0.0

In [278]:
df_1.fillna(0) #fillna 0 is more relevant due to the empty spots being times were a workout was not initiatiated
#Reminder: Eliminate Row 0 begining at column 1

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,0,720.0,6088.0,5008.0,0.0,4280.0,14830.0,9825.0,8850.0
1,"8,690",390.0,6036.0,10235.0,0.0,4830.0,20030.0,10350.0,3450.0
2,"6,085",0.0,7275.0,2400.0,0.0,4590.0,10800.0,12120.0,3000.0
3,"2,360",1560.0,0.0,3840.0,0.0,0.0,12100.0,11820.0,0.0
4,"7,300",1440.0,0.0,4080.0,0.0,0.0,5300.0,4500.0,0.0
5,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,"7,915",580.0,0.0,0.0,0.0,0.0,7080.0,1760.0,5400.0
9,"10,441",2920.0,3600.0,0.0,0.0,3960.0,4560.0,4840.0,6300.0
10,"7,798",3240.0,3600.0,8260.0,0.0,3230.0,7400.0,7680.0,7230.0
11,"13,054",3290.0,4865.0,5900.0,0.0,1950.0,9150.0,8040.0,6300.0
12,"5,665",2050.0,1050.0,5600.0,0.0,1490.0,0.0,0.0,0.0
13,"11,595",0.0,0.0,6360.0,0.0,0.0,10710.0,8240.0,6300.0
14,"10,251",300.0,0.0,0.0,0.0,0.0,3310.0,0.0,0.0
15,0,3610.0,4995.0,6880.0,0.0,2120.0,0.0,3060.0,0.0
16,"8,790",0.0,0.0,6080.0,0.0,1650.0,0.0,0.0,0.0
17,"5,500",1765.0,1170.0,7270.0,2350.0,2630.0,8470.0,2400.0,0.0
18,"8,148",3060.0,1960.0,9270.0,2500.0,2820.0,10250.0,2020.0,2265.0
19,"9,188",3590.0,2150.0,9490.0,4050.0,3338.0,0.0,0.0,0.0
20,"8,755",0.0,0.0,0.0,0.0,0.0,5690.0,2230.0,0.0
21,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,"6,910",0.0,1150.0,10125.0,0.0,1730.0,13132.0,1410.0,940.0
25,0,0.0,1710.0,0.0,0.0,3026.0,11802.0,0.0,2590.0
26,"7,910",1942.0,1138.0,5135.0,2700.0,2830.0,14370.0,4855.0,2405.0
27,"6,170",0.0,2867.0,10775.0,0.0,2210.0,16028.0,5610.0,9315.0
28,"11,440",0.0,2722.0,0.0,0.0,2950.0,13980.0,1850.0,12460.0
29,"9,842",5948.0,0.0,13873.0,4550.0,0.0,0.0,0.0,0.0
30,"10,520",4618.0,5090.0,15970.0,6930.0,3310.0,5030.0,0.0,0.0
31,"12,434",7264.0,5700.0,14267.0,9645.0,3390.0,17568.0,5425.0,9420.0
32,"12,075",9374.0,7070.0,13150.0,10630.0,4168.0,16230.0,4400.0,12420.0
33,0,0.0,7070.0,0.0,0.0,4168.0,14585.0,2590.0,0.0
34,"15,804",9740.0,7878.0,12710.0,10630.0,4000.0,15740.0,4270.0,9315.0
35,"13,600",8290.0,3740.0,0.0,0.0,3460.0,0.0,0.0,0.0
36,0,7800.0,4220.0,5400.0,10530.0,3505.0,5760.0,0.0,0.0
37,"16,595",7460.0,3620.0,11430.0,8100.0,4250.0,10765.0,5850.0,8100.0
38,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Total Sets

In [230]:
muscles = ["Chest","Shoulders", "Triceps", "Upper Back", "Traps", "Biceps", "Quads", "Hamstrings", "Calves"]
weeks = df.columns[1:]
total_sets_table = pd.DataFrame(index=weeks, columns=muscles)

In [234]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df)
  muscle_block = df.iloc[muscle_idx+2 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Total Sets"
  total_sets_row = muscle_block[mask].iloc[0, 1:]
  total_sets_table[muscle] = total_sets_row.values.flatten()

In [243]:
total_sets_table.to_csv('total_sets_table.csv', index=False)
from google.colab import files
files.download('total_sets_table.csv')

## Total Reps

In [188]:
#begining of Total Reps Table, mirroring total load table until automation/indexing is complete
col0 = df.iloc[:, 0]
metric_names = ['Total Load', 'Total Sets', 'Total Reps', 'Weights Per Rep']
muscles = col0[~col0.isna() & ~col0.str.strip().isin(metric_names)].str.strip().tolist()

In [211]:
muscles = ["Chest","Shoulders", "Triceps", "Upper Back", "Traps", "Biceps", "Quads", "Hamstrings", "Calves"]
weeks = df.columns[1:]
total_reps_table = pd.DataFrame(index=weeks, columns=muscles)

In [212]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df)
  muscle_block = df.iloc[muscle_idx+3 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Total Reps"
  total_reps_row = muscle_block[mask].iloc[0, 1:]
  total_reps_table[muscle] = total_reps_row.values.flatten()

In [214]:
total_reps_table.to_csv('total_reps_table.csv', index=False)
from google.colab import files
files.download('total_reps_table.csv')

## Weights Per Rep

In [220]:
muscles = ["Chest","Shoulders", "Triceps", "Upper Back", "Traps", "Biceps", "Quads", "Hamstrings", "Calves"]
weeks = df.columns[1:]
weights_per_rep_table = pd.DataFrame(index=weeks, columns=muscles)

In [221]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df)
  muscle_block = df.iloc[muscle_idx+4 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Weights Per Rep"
  weights_per_rep_row = muscle_block[mask].iloc[0, 1:]
  weights_per_rep_table[muscle] = weights_per_rep_row.values.flatten()

In [222]:
weights_per_rep_table.to_csv('weights_per_rep.csv', index=False)
from google.colab import files
files.download('weights_per_rep.csv')

In [227]:
df_4.fillna(0) #fillna 0 is more relevant due to the empty spots being times were a workout was not initiatiated

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,0.0,15.0,69.0,45.0,0.0,16.0,151.0,76.0,148.0
1,62.0,10.0,82.0,49.0,0.0,24.0,139.0,104.0,99.0
2,45.0,0.0,58.0,44.0,0.0,25.0,154.0,118.0,50.0
3,27.0,13.0,0.0,48.0,0.0,0.0,242.0,164.0,0.0
4,57.0,15.0,0.0,41.0,0.0,0.0,265.0,180.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,63.0,10.0,0.0,0.0,0.0,0.0,148.0,55.0,120.0
9,86.0,34.0,53.0,0.0,0.0,26.0,76.0,86.0,140.0
10,41.0,22.0,30.0,71.0,0.0,24.0,154.0,98.0,127.0
11,69.0,23.0,40.0,67.0,0.0,26.0,117.0,99.0,140.0
12,72.0,29.0,16.0,68.0,0.0,27.0,0.0,0.0,0.0
13,77.0,0.0,0.0,71.0,0.0,0.0,122.0,81.0,140.0
14,52.0,10.0,0.0,0.0,0.0,0.0,110.0,0.0,0.0
15,0.0,23.0,44.0,65.0,0.0,31.0,0.0,153.0,0.0
16,70.0,0.0,0.0,76.0,0.0,28.0,0.0,0.0,0.0
17,53.0,15.0,21.0,44.0,50.0,22.0,128.0,75.0,0.0
18,45.0,26.0,30.0,56.0,50.0,22.0,99.0,43.0,40.0
19,51.0,25.0,26.0,51.0,90.0,25.0,0.0,0.0,0.0
20,53.0,0.0,0.0,0.0,0.0,0.0,92.0,47.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,29.0,0.0,14.0,56.0,0.0,13.0,90.0,30.0,20.0
25,0.0,0.0,30.0,0.0,0.0,26.0,179.0,0.0,70.0
26,37.0,24.0,28.0,49.0,90.0,24.0,127.0,52.0,65.0
27,38.0,0.0,39.0,51.0,0.0,26.0,125.0,67.0,207.0
28,55.0,0.0,42.0,0.0,0.0,24.0,155.0,50.0,152.0
29,45.0,21.0,0.0,50.0,55.0,0.0,0.0,0.0,0.0
30,45.0,19.0,35.0,56.0,71.0,21.0,74.0,0.0,0.0
31,52.0,22.0,32.0,43.0,110.0,23.0,113.0,48.0,157.0
32,47.0,27.0,39.0,61.0,112.0,29.0,91.0,44.0,207.0
33,0.0,0.0,39.0,0.0,0.0,29.0,111.0,70.0,0.0
34,60.0,27.0,39.0,52.0,112.0,26.0,125.0,45.0,207.0
35,53.0,22.0,26.0,0.0,0.0,22.0,0.0,0.0,0.0
36,0.0,20.0,28.0,47.0,112.0,23.0,69.0,0.0,0.0
37,44.0,19.0,18.0,52.0,135.0,20.0,59.0,39.0,108.0
38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Exploratory Analysis

Total Load

In [311]:
#verification of new table Total Load table
df_1.info()
df_1.head()
df_1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chest       31 non-null     float64
 1   Shoulders   32 non-null     float64
 2   Triceps     32 non-null     float64
 3   Upper Back  32 non-null     float64
 4   Traps       32 non-null     float64
 5   Biceps      32 non-null     float64
 6   Quads       32 non-null     float64
 7   Hamstrings  32 non-null     float64
 8   Calves      32 non-null     float64
dtypes: float64(9)
memory usage: 2.9 KB

Chest         9
Shoulders     8
Triceps       8
Upper Back    8
Traps         8
Biceps        8
Quads         8
Hamstrings    8
Calves        8
dtype: int64

In [300]:
df_1.describe()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
count,31.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,8220.483871,2842.218750,3023.875000,6359.625000,2269.218750,2496.406250,8895.937500,3910.781250,3626.875000
std,4409.574635,3114.730618,2576.544169,4922.138656,3745.637486,1585.339891,5961.048993,3731.836681,4153.085085
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6127.500000,0.000000,787.500000,1800.000000,0.000000,1610.000000,4912.500000,0.000000,0.000000
50%,8690.000000,1853.500000,2794.500000,5990.000000,0.000000,2890.000000,9700.000000,2825.000000,2335.000000
75%,10980.000000,3862.000000,5018.750000,10152.500000,3037.500000,3618.750000,14077.500000,5670.000000,6532.500000
max,16595.000000,9740.000000,7878.000000,15970.000000,10630.000000,4830.000000,20030.000000,12120.000000,12460.000000

In [291]:
df_1.cumsum()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,0.0,720.0,6088.0,5008.0,0.0,4280.0,14830.0,9825.0,8850.0
1,8690.0,1110.0,12124.0,15243.0,0.0,9110.0,34860.0,20175.0,12300.0
2,14775.0,1110.0,19399.0,17643.0,0.0,13700.0,45660.0,32295.0,15300.0
3,17135.0,2670.0,19399.0,21483.0,0.0,13700.0,57760.0,44115.0,15300.0
4,24435.0,4110.0,19399.0,25563.0,0.0,13700.0,63060.0,48615.0,15300.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,32350.0,4690.0,19399.0,25563.0,0.0,13700.0,70140.0,50375.0,20700.0
9,42791.0,7610.0,22999.0,25563.0,0.0,17660.0,74700.0,55215.0,27000.0
10,50589.0,10850.0,26599.0,33823.0,0.0,20890.0,82100.0,62895.0,34230.0
11,63643.0,14140.0,31464.0,39723.0,0.0,22840.0,91250.0,70935.0,40530.0
12,69308.0,16190.0,32514.0,45323.0,0.0,24330.0,91250.0,70935.0,40530.0
13,80903.0,16190.0,32514.0,51683.0,0.0,24330.0,101960.0,79175.0,46830.0
14,91154.0,16490.0,32514.0,51683.0,0.0,24330.0,105270.0,79175.0,46830.0
15,91154.0,20100.0,37509.0,58563.0,0.0,26450.0,105270.0,82235.0,46830.0
16,99944.0,20100.0,37509.0,64643.0,0.0,28100.0,105270.0,82235.0,46830.0
17,105444.0,21865.0,38679.0,71913.0,2350.0,30730.0,113740.0,84635.0,46830.0
18,113592.0,24925.0,40639.0,81183.0,4850.0,33550.0,123990.0,86655.0,49095.0
19,122780.0,28515.0,42789.0,90673.0,8900.0,36888.0,123990.0,86655.0,49095.0
20,131535.0,28515.0,42789.0,90673.0,8900.0,36888.0,129680.0,88885.0,49095.0
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,138445.0,28515.0,43939.0,100798.0,8900.0,38618.0,142812.0,90295.0,50035.0
25,NaN,28515.0,45649.0,100798.0,8900.0,41644.0,154614.0,90295.0,52625.0
26,146355.0,30457.0,46787.0,105933.0,11600.0,44474.0,168984.0,95150.0,55030.0
27,152525.0,30457.0,49654.0,116708.0,11600.0,46684.0,185012.0,100760.0,64345.0
28,163965.0,30457.0,52376.0,116708.0,11600.0,49634.0,198992.0,102610.0,76805.0
29,173807.0,36405.0,52376.0,130581.0,16150.0,49634.0,198992.0,102610.0,76805.0
30,184327.0,41023.0,57466.0,146551.0,23080.0,52944.0,204022.0,102610.0,76805.0
31,196761.0,48287.0,63166.0,160818.0,32725.0,56334.0,221590.0,108035.0,86225.0
32,208836.0,57661.0,70236.0,173968.0,43355.0,60502.0,237820.0,112435.0,98645.0
33,208836.0,57661.0,77306.0,173968.0,43355.0,64670.0,252405.0,115025.0,98645.0
34,224640.0,67401.0,85184.0,186678.0,53985.0,68670.0,268145.0,119295.0,107960.0
35,238240.0,75691.0,88924.0,186678.0,53985.0,72130.0,268145.0,119295.0,107960.0
36,238240.0,83491.0,93144.0,192078.0,64515.0,75635.0,273905.0,119295.0,107960.0
37,254835.0,90951.0,96764.0,203508.0,72615.0,79885.0,284670.0,125145.0,116060.0
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Total Sets

In [310]:
#verification of new table Total Sets table
df_2 = pd.read_csv('total_sets_table.csv')
df_2.info()
df_2.head()
df_2.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chest       31 non-null     float64
 1   Shoulders   32 non-null     float64
 2   Triceps     32 non-null     float64
 3   Upper Back  32 non-null     float64
 4   Traps       32 non-null     float64
 5   Biceps      32 non-null     float64
 6   Quads       32 non-null     float64
 7   Hamstrings  32 non-null     float64
 8   Calves      32 non-null     float64
dtypes: float64(9)
memory usage: 2.9 KB

Chest         9
Shoulders     8
Triceps       8
Upper Back    8
Traps         8
Biceps        8
Quads         8
Hamstrings    8
Calves        8
dtype: int64

In [299]:
df_2.describe()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
count,31.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,13.580645,10.031250,6.937500,10.750000,1.875000,8.312500,7.187500,4.843750,2.062500
std,6.849692,9.348053,5.512084,8.806156,2.926519,4.973721,4.815549,4.414853,1.966453
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12.000000,0.000000,2.250000,3.750000,0.000000,6.000000,4.750000,0.000000,0.000000
50%,14.000000,8.500000,6.000000,9.500000,0.000000,10.000000,7.000000,3.000000,3.000000
75%,18.000000,15.750000,10.500000,15.250000,3.000000,12.000000,10.250000,8.250000,3.250000
max,27.000000,27.000000,19.000000,31.000000,8.000000,14.000000,17.000000,18.000000,6.000000

In [303]:
df_2.cumsum()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,0.0,4.0,8.0,11.0,0.0,11.0,10.0,18.0,4.0
1,15.0,8.0,14.0,32.0,0.0,25.0,25.0,28.0,7.0
2,29.0,8.0,23.0,37.0,0.0,38.0,32.0,40.0,11.0
3,37.0,17.0,23.0,45.0,0.0,38.0,37.0,49.0,11.0
4,50.0,25.0,23.0,53.0,0.0,38.0,39.0,54.0,11.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,62.0,30.0,23.0,53.0,0.0,38.0,45.0,57.0,14.0
9,75.0,39.0,29.0,53.0,0.0,50.0,51.0,63.0,17.0
10,88.0,54.0,39.0,65.0,0.0,62.0,57.0,69.0,21.0
11,106.0,68.0,49.0,73.0,0.0,70.0,66.0,78.0,24.0
12,114.0,75.0,55.0,81.0,0.0,76.0,66.0,78.0,24.0
13,128.0,75.0,55.0,90.0,0.0,76.0,76.0,87.0,27.0
14,146.0,78.0,55.0,90.0,0.0,76.0,80.0,87.0,27.0
15,146.0,91.0,65.0,100.0,0.0,82.0,80.0,90.0,27.0
16,158.0,91.0,65.0,107.0,0.0,88.0,80.0,90.0,27.0
17,169.0,104.0,71.0,121.0,3.0,97.0,87.0,93.0,27.0
18,183.0,114.0,77.0,135.0,6.0,107.0,94.0,96.0,32.0
19,197.0,124.0,83.0,151.0,9.0,117.0,94.0,96.0,32.0
20,209.0,124.0,83.0,151.0,9.0,117.0,99.0,99.0,32.0
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,224.0,124.0,89.0,165.0,9.0,128.0,110.0,102.0,35.0
25,NaN,124.0,93.0,165.0,9.0,138.0,117.0,102.0,38.0
26,239.0,131.0,96.0,173.0,12.0,148.0,126.0,109.0,41.0
27,251.0,131.0,102.0,190.0,12.0,155.0,138.0,115.0,44.0
28,270.0,131.0,107.0,190.0,12.0,165.0,147.0,118.0,50.0
29,287.0,151.0,107.0,216.0,18.0,165.0,147.0,118.0,50.0
30,306.0,169.0,119.0,243.0,25.0,178.0,154.0,118.0,50.0
31,327.0,193.0,134.0,274.0,32.0,191.0,167.0,127.0,54.0
32,350.0,220.0,150.0,294.0,40.0,204.0,184.0,135.0,58.0
33,350.0,220.0,166.0,294.0,40.0,217.0,198.0,138.0,58.0
34,374.0,246.0,185.0,318.0,48.0,231.0,211.0,146.0,61.0
35,394.0,271.0,197.0,318.0,48.0,243.0,211.0,146.0,61.0
36,394.0,296.0,209.0,329.0,56.0,254.0,218.0,146.0,61.0
37,421.0,321.0,222.0,344.0,60.0,266.0,230.0,155.0,66.0
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Total Reps

In [295]:
#verification of new table total rep
df_3 = pd.read_csv('total_reps_table.csv')
df_3.info()
df_3.head()
df_3.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chest       31 non-null     float64
 1   Shoulders   32 non-null     float64
 2   Triceps     32 non-null     float64
 3   Upper Back  32 non-null     float64
 4   Traps       32 non-null     float64
 5   Biceps      32 non-null     float64
 6   Quads       32 non-null     float64
 7   Hamstrings  31 non-null     float64
 8   Calves      32 non-null     float64
dtypes: float64(9)
memory usage: 2.9 KB

In [296]:
df_3.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chest       31 non-null     float64
 1   Shoulders   32 non-null     float64
 2   Triceps     32 non-null     float64
 3   Upper Back  32 non-null     float64
 4   Traps       32 non-null     float64
 5   Biceps      32 non-null     float64
 6   Quads       32 non-null     float64
 7   Hamstrings  31 non-null     float64
 8   Calves      32 non-null     float64
dtypes: float64(9)
memory usage: 2.9 KB

In [292]:
df_3.cumsum()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,0.0,48.0,88.0,112.0,0.0,266.0,98.0,130.0,60.0
1,141.0,87.0,162.0,321.0,0.0,470.0,242.0,230.0,95.0
2,277.0,87.0,287.0,375.0,0.0,653.0,312.0,333.0,155.0
3,365.0,207.0,287.0,455.0,0.0,653.0,362.0,405.0,155.0
4,494.0,303.0,287.0,554.0,0.0,653.0,382.0,430.0,155.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,619.0,361.0,287.0,554.0,0.0,653.0,430.0,462.0,200.0
9,740.0,447.0,355.0,554.0,0.0,803.0,490.0,518.0,245.0
10,932.0,597.0,475.0,671.0,0.0,940.0,538.0,596.0,302.0
11,1122.0,739.0,596.0,759.0,0.0,1016.0,616.0,677.0,347.0
12,1201.0,809.0,662.0,841.0,0.0,1072.0,616.0,677.0,347.0
13,1352.0,809.0,662.0,930.0,0.0,1072.0,704.0,779.0,392.0
14,1550.0,839.0,662.0,930.0,0.0,1072.0,734.0,NaN,392.0
15,1550.0,993.0,776.0,1036.0,0.0,1140.0,734.0,799.0,392.0
16,1675.0,993.0,776.0,1116.0,0.0,1200.0,734.0,799.0,392.0
17,1779.0,1114.0,831.0,1282.0,47.0,1318.0,800.0,831.0,392.0
18,1959.0,1233.0,897.0,1448.0,97.0,1449.0,904.0,878.0,449.0
19,2139.0,1375.0,981.0,1634.0,142.0,1580.0,904.0,878.0,449.0
20,2304.0,1375.0,981.0,1634.0,142.0,1580.0,966.0,925.0,449.0
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2539.0,1375.0,1065.0,1814.0,142.0,1716.0,1112.0,972.0,496.0
25,NaN,1375.0,1122.0,1814.0,142.0,1834.0,1178.0,972.0,533.0
26,2751.0,1457.0,1162.0,1918.0,172.0,1950.0,1291.0,1066.0,570.0
27,2914.0,1457.0,1235.0,2128.0,172.0,2036.0,1419.0,1150.0,615.0
28,3123.0,1457.0,1300.0,2128.0,172.0,2159.0,1509.0,1187.0,697.0
29,3342.0,1736.0,1300.0,2408.0,254.0,2159.0,1509.0,1187.0,697.0
30,3577.0,1984.0,1445.0,2693.0,351.0,2315.0,1577.0,1187.0,697.0
31,3814.0,2311.0,1624.0,3023.0,439.0,2462.0,1732.0,1300.0,757.0
32,4073.0,2662.0,1807.0,3238.0,534.0,2607.0,1910.0,1400.0,817.0
33,4073.0,2662.0,1990.0,3238.0,534.0,2752.0,2041.0,1437.0,817.0
34,4337.0,3022.0,2194.0,3483.0,629.0,2907.0,2167.0,1532.0,862.0
35,4592.0,3391.0,2336.0,3483.0,629.0,3066.0,2167.0,1532.0,862.0
36,4592.0,3780.0,2487.0,3598.0,723.0,3217.0,2251.0,1532.0,862.0
37,4965.0,4179.0,2683.0,3817.0,783.0,3429.0,2434.0,1682.0,937.0
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Weights Per Rep

In [307]:
#verification of new table weights per table
df_4 = pd.read_csv('weights_per_rep.csv')
df_4.info()
df_4.head()
df_4.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Chest       27 non-null     float64
 1   Shoulders   23 non-null     float64
 2   Triceps     24 non-null     float64
 3   Upper Back  24 non-null     float64
 4   Traps       11 non-null     float64
 5   Biceps      25 non-null     float64
 6   Quads       26 non-null     float64
 7   Hamstrings  23 non-null     float64
 8   Calves      18 non-null     float64
dtypes: float64(9)
memory usage: 2.9 KB

Chest         13
Shoulders     17
Triceps       16
Upper Back    16
Traps         29
Biceps        15
Quads         14
Hamstrings    17
Calves        22
dtype: int64

In [308]:
df_4.describe()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
count,27.000000,23.000000,24.000000,24.000000,11.000000,25.000000,26.000000,23.000000,18.000000
mean,52.888889,20.478261,36.583333,54.708333,89.727273,24.080000,127.500000,79.304348,122.055556
std,13.973418,6.409294,16.161997,10.097263,29.431585,3.925557,47.881729,41.516081,56.603338
min,27.000000,10.000000,14.000000,41.000000,50.000000,13.000000,59.000000,30.000000,20.000000
25%,45.000000,15.000000,27.500000,47.750000,63.000000,22.000000,93.750000,47.500000,77.250000
50%,52.000000,22.000000,33.500000,51.500000,90.000000,24.000000,123.500000,70.000000,133.500000
75%,61.000000,24.500000,40.500000,62.000000,112.000000,26.000000,150.250000,98.500000,151.000000
max,86.000000,34.000000,82.000000,76.000000,135.000000,31.000000,265.000000,180.000000,207.000000

In [309]:
df_4.cumsum()

,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
0,NaN,15.0,69.0,45.0,NaN,16.0,151.0,76.0,148.0
1,62.0,25.0,151.0,94.0,NaN,40.0,290.0,180.0,247.0
2,107.0,NaN,209.0,138.0,NaN,65.0,444.0,298.0,297.0
3,134.0,38.0,NaN,186.0,NaN,NaN,686.0,462.0,NaN
4,191.0,53.0,NaN,227.0,NaN,NaN,951.0,642.0,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,254.0,63.0,NaN,NaN,NaN,NaN,1099.0,697.0,417.0
9,340.0,97.0,262.0,NaN,NaN,91.0,1175.0,783.0,557.0
10,381.0,119.0,292.0,298.0,NaN,115.0,1329.0,881.0,684.0
11,450.0,142.0,332.0,365.0,NaN,141.0,1446.0,980.0,824.0
12,522.0,171.0,348.0,433.0,NaN,168.0,NaN,NaN,NaN
13,599.0,NaN,NaN,504.0,NaN,NaN,1568.0,1061.0,964.0
14,651.0,181.0,NaN,NaN,NaN,NaN,1678.0,NaN,NaN
15,NaN,204.0,392.0,569.0,NaN,199.0,NaN,1214.0,NaN
16,721.0,NaN,NaN,645.0,NaN,227.0,NaN,NaN,NaN
17,774.0,219.0,413.0,689.0,50.0,249.0,1806.0,1289.0,NaN
18,819.0,245.0,443.0,745.0,100.0,271.0,1905.0,1332.0,1004.0
19,870.0,270.0,469.0,796.0,190.0,296.0,NaN,NaN,NaN
20,923.0,NaN,NaN,NaN,NaN,NaN,1997.0,1379.0,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,952.0,NaN,483.0,852.0,NaN,309.0,2087.0,1409.0,1024.0
25,NaN,NaN,513.0,NaN,NaN,335.0,2266.0,NaN,1094.0
26,989.0,294.0,541.0,901.0,280.0,359.0,2393.0,1461.0,1159.0
27,1027.0,NaN,580.0,952.0,NaN,385.0,2518.0,1528.0,1366.0
28,1082.0,NaN,622.0,NaN,NaN,409.0,2673.0,1578.0,1518.0
29,1127.0,315.0,NaN,1002.0,335.0,NaN,NaN,NaN,NaN
30,1172.0,334.0,657.0,1058.0,406.0,430.0,2747.0,NaN,NaN
31,1224.0,356.0,689.0,1101.0,516.0,453.0,2860.0,1626.0,1675.0
32,1271.0,383.0,728.0,1162.0,628.0,482.0,2951.0,1670.0,1882.0
33,NaN,NaN,767.0,NaN,NaN,511.0,3062.0,1740.0,NaN
34,1331.0,410.0,806.0,1214.0,740.0,537.0,3187.0,1785.0,2089.0
35,1384.0,432.0,832.0,NaN,NaN,559.0,NaN,NaN,NaN
36,NaN,452.0,860.0,1261.0,852.0,582.0,3256.0,NaN,NaN
37,1428.0,471.0,878.0,1313.0,987.0,602.0,3315.0,1824.0,2197.0
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Organizing 2024-2025

## Formating Begin

In [419]:
df_2024 = pd.read_csv('2024-2025.csv')
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 53 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   2024-2025      62 non-null     object
 1   First 8 Week   62 non-null     object
 2   Unnamed: 2     54 non-null     object
 3   Unnamed: 3     54 non-null     object
 4   Unnamed: 4     54 non-null     object
 5   Unnamed: 5     54 non-null     object
 6   Unnamed: 6     54 non-null     object
 7   Unnamed: 7     54 non-null     object
 8   Unnamed: 8     50 non-null     object
 9   Second 8 Week  59 non-null     object
 10  Unnamed: 10    54 non-null     object
 11  Unnamed: 11    54 non-null     object
 12  Unnamed: 12    54 non-null     object
 13  Unnamed: 13    51 non-null     object
 14  Unnamed: 14    54 non-null     object
 15  Unnamed: 15    54 non-null     object
 16  Unnamed: 16    51 non-null     object
 17  Third 8 Week   62 non-null     object
 18  Unnamed: 18    54 non-null     object
 19  Unnamed: 19    54 non-null     object
 20  Unnamed: 20    54 non-null     object
 21  Unnamed: 21    49 non-null     object
 22  Unnamed: 22    54 non-null     object
 23  Unnamed: 23    51 non-null     object
 24  Unnamed: 24    47 non-null     object
 25  Fourth 8 Week  62 non-null     object
 26  Unnamed: 26    50 non-null     object
 27  Unnamed: 27    54 non-null     object
 28  Unnamed: 28    52 non-null     object
 29  Unnamed: 29    53 non-null     object
 30  Unnamed: 30    50 non-null     object
 31  Unnamed: 31    45 non-null     object
 32  Unnamed: 32    45 non-null     object
 33  Fifth 8 Week   60 non-null     object
 34  Unnamed: 34    52 non-null     object
 35  Unnamed: 35    52 non-null     object
 36  Unnamed: 36    54 non-null     object
 37  Sixth 8 Week   59 non-null     object
 38  Unnamed: 38    52 non-null     object
 39  Unnamed: 39    54 non-null     object
 40  Unnamed: 40    54 non-null     object
 41  Unnamed: 41    54 non-null     object
 42  Unnamed: 42    54 non-null     object
 43  Unnamed: 43    54 non-null     object
 44  Unnamed: 44    54 non-null     object
 45  Sevnth 8 Week  62 non-null     object
 46  Unnamed: 46    54 non-null     object
 47  Unnamed: 47    54 non-null     object
 48  Unnamed: 48    54 non-null     object
 49  Unnamed: 49    54 non-null     object
 50  Unnamed: 50    52 non-null     object
 51  Unnamed: 51    54 non-null     object
 52  Unnamed: 52    54 non-null     object
dtypes: object(53)
memory usage: 25.8+ KB

In [420]:
df_2024.describe()

,2024-2025,First 8 Week,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second 8 Week,...,Unnamed: 43,Unnamed: 44,Sevnth 8 Week,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
count,62,62,54,54,54,54,54,54,50,59,...,54,54,62,54,54,54,54,52,54,54
unique,16,35,43,42,38,38,42,42,26,31,...,43,43,45,45,43,41,45,39,41,44
top,Total Load,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,0,0,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
freq,9,9,9,9,9,9,9,9,16,12,...,9,9,9,9,9,9,9,9,9,9

In [421]:
df_2024.head()

,2024-2025,First 8 Week,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second 8 Week,...,Unnamed: 43,Unnamed: 44,Sevnth 8 Week,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,Chest,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,Total Load,"5,030","6,171","6,856","7,872","8,540","8,619","9,502","9,660",0,...,"15,139","16,178","15,494","11,876","14,274","11,819","13,075","10,840","15,430","13,962"
2,Total Sets,9,11,10,10,12,13,12,13,0,...,14,15,15,15,14,14,14,14,14,15
3,Total Reps,90,95,98,92,90,89,94,92,0,...,112,115,109,107,93,101,87,102,119,110
4,Weights Per Rep,56,65,70,86,95,97,101,105,0,...,135,141,142,111,153,117,150,106,130,127

In [422]:
df_2024.loc[0]

2024-2025         Chest
First 8 Week     Week 1
Unnamed: 2       Week 2
Unnamed: 3       Week 3
Unnamed: 4       Week 4
Unnamed: 5       Week 5
Unnamed: 6       Week 6
Unnamed: 7       Week 7
Unnamed: 8       Week 8
Second 8 Week    Week 1
Unnamed: 10      Week 2
Unnamed: 11      Week 3
Unnamed: 12      Week 4
Unnamed: 13      Week 5
Unnamed: 14      Week 6
Unnamed: 15      Week 7
Unnamed: 16      Week 8
Third 8 Week     Week 1
Unnamed: 18      Week 2
Unnamed: 19      Week 3
Unnamed: 20      Week 4
Unnamed: 21      Week 5
Unnamed: 22      Week 6
Unnamed: 23      Week 7
Unnamed: 24      Week 8
Fourth 8 Week    Week 1
Unnamed: 26      Week 2
Unnamed: 27      Week 3
Unnamed: 28      Week 4
Unnamed: 29      Week 5
Unnamed: 30      Week 6
Unnamed: 31      Week 7
Unnamed: 32      Week 8
Fifth 8 Week     Week 1
Unnamed: 34      Week 2
Unnamed: 35      Week 3
Unnamed: 36      Week 4
Sixth 8 Week     Week 1
Unnamed: 38      Week 2
Unnamed: 39      Week 3
Unnamed: 40      Week 4
Unnamed: 41      Week 5
Unnamed: 42      Week 6
Unnamed: 43      Week 7
Unnamed: 44      Week 8
Sevnth 8 Week    Week 1
Unnamed: 46      Week 2
Unnamed: 47      Week 3
Unnamed: 48      Week 4
Unnamed: 49      Week 5
Unnamed: 50      Week 6
Unnamed: 51      Week 7
Unnamed: 52      Week 8
Name: 0, dtype: object

In [423]:
df_2024.isnull().sum()

2024-2025         0
First 8 Week      0
Unnamed: 2        8
Unnamed: 3        8
Unnamed: 4        8
Unnamed: 5        8
Unnamed: 6        8
Unnamed: 7        8
Unnamed: 8       12
Second 8 Week     3
Unnamed: 10       8
Unnamed: 11       8
Unnamed: 12       8
Unnamed: 13      11
Unnamed: 14       8
Unnamed: 15       8
Unnamed: 16      11
Third 8 Week      0
Unnamed: 18       8
Unnamed: 19       8
Unnamed: 20       8
Unnamed: 21      13
Unnamed: 22       8
Unnamed: 23      11
Unnamed: 24      15
Fourth 8 Week     0
Unnamed: 26      12
Unnamed: 27       8
Unnamed: 28      10
Unnamed: 29       9
Unnamed: 30      12
Unnamed: 31      17
Unnamed: 32      17
Fifth 8 Week      2
Unnamed: 34      10
Unnamed: 35      10
Unnamed: 36       8
Sixth 8 Week      3
Unnamed: 38      10
Unnamed: 39       8
Unnamed: 40       8
Unnamed: 41       8
Unnamed: 42       8
Unnamed: 43       8
Unnamed: 44       8
Sevnth 8 Week     0
Unnamed: 46       8
Unnamed: 47       8
Unnamed: 48       8
Unnamed: 49       8
Unnamed: 50      10
Unnamed: 51       8
Unnamed: 52       8
dtype: int64

In [424]:
df_2024.shape

(62, 53)

In [425]:
list(df_2024.columns) #identifying columns needed for renaming

['2024-2025',
 'First 8 Week',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Second 8 Week',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Third 8 Week',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Fourth 8 Week',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Fifth 8 Week',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Sixth 8 Week',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Sevnth 8 Week',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Unnamed: 52']

In [426]:
df_2024.iloc[:, 1:62]

,First 8 Week,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second 8 Week,Unnamed: 10,...,Unnamed: 43,Unnamed: 44,Sevnth 8 Week,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,Week 2,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,"5,030","6,171","6,856","7,872","8,540","8,619","9,502","9,660",0,"9,044",...,"15,139","16,178","15,494","11,876","14,274","11,819","13,075","10,840","15,430","13,962"
2,9,11,10,10,12,13,12,13,0,11,...,14,15,15,15,14,14,14,14,14,15
3,90,95,98,92,90,89,94,92,0,101,...,112,115,109,107,93,101,87,102,119,110
4,56,65,70,86,95,97,101,105,0,90,...,135,141,142,111,153,117,150,106,130,127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,"17,340","24,315","26,475","32,445","55,386","61,398","67,880",0,"22,806","23,925",...,"53,250","53,325","29,025","33,765","35,460","37,920","24,360","7,800","38,100","46,860"
58,9,12,12,12,15,15,15,0,9,9,...,12,12,5,8,8,8,4,3,4,8
59,132,180,180,180,270,270,270,0,138,135,...,180,180,75,117,120,120,60,22,120,120
60,131,135,147,180,205,227,251,0,165,177,...,296,296,387,289,296,316,406,355,318,391
61,0%,3%,8%,18%,12%,10%,10%,NaN,-52%,7%,...,11%,0%,31%,-34%,2%,6%,22%,-14%,-12%,19%

In [437]:
#Changing the Columns to better identify weeks and sections(Week 1.1 is First Grouping First Week)
df_2024.rename(columns={'First 8 Week': 'Week 1.1',
 'Unnamed: 2': 'Week 1.2',
 'Unnamed: 3': 'Week 1.3',
 'Unnamed: 4': 'Week 1.14',
 'Unnamed: 5': 'Week 1.5',
 'Unnamed: 6': 'Week 1.6',
 'Unnamed: 7': 'Week 1.7',
 'Unnamed: 8': 'Week 1.8',
 'Second 8 Week': 'Week 2.1',
 'Unnamed: 10': 'Week 2.2',
 'Unnamed: 11': 'Week 2.3',
 'Unnamed: 12': 'Week 2.4',
 'Unnamed: 13': 'Week 2.5',
 'Unnamed: 14': 'Week 2.6',
 'Unnamed: 15': 'Week 2.7',
 'Unnamed: 16': 'Week 2.8',
 'Third 8 Week': 'Week 3.1',
 'Unnamed: 18': 'Week 3.2',
 'Unnamed: 19': 'Week 3.3',
 'Unnamed: 20': 'Week 3.4',
 'Unnamed: 21': 'Week 3.5',
 'Unnamed: 22': 'Week 3.6',
 'Unnamed: 23': 'Week 3.7',
 'Unnamed: 24': 'Week 3.8',
 'Fourth 8 Week': 'Week 4.1',
 'Unnamed: 26': 'Week 4.2',
 'Unnamed: 27': 'Week 4.3',
 'Unnamed: 28': 'Week 4.4',
 'Unnamed: 29': 'Week 4.5',
 'Unnamed: 30': 'Week 4.6',
 'Unnamed: 31': 'Week 4.7',
 'Unnamed: 32': 'Week 4.8',
 'Fifth 8 Week': 'Week 5.1',
 'Unnamed: 34': 'Week 5.2',
 'Unnamed: 35': 'Week 5.3',
 'Unnamed: 36': 'Week 5.4',
 'Sixth 8 Week': 'Week 6.1',
 'Unnamed: 38': 'Week 6.2',
 'Unnamed: 39': 'Week 6.3',
 'Unnamed: 40': 'Week 6.4',
 'Unnamed: 41': 'Week 6.5',
 'Unnamed: 42': 'Week 6.6',
 'Unnamed: 43': 'Week 6.7',
 'Unnamed: 44': 'Week 6.8',
 'Sevnth 8 Week': 'Week 7.1',
 'Unnamed: 46': 'Week 7.2',
 'Unnamed: 47': 'Week 7.3',
 'Unnamed: 48': 'Week 7.4',
 'Unnamed: 49': 'Week 7.5',
 'Unnamed: 50': 'Week 7.6',
 'Unnamed: 51': 'Week 7.7',
 'Unnamed: 52': 'Week 7.8'}, inplace=True)

In [438]:
print(df_2024.columns) #verification of rename

Index(['2024-2025', 'Week 1.1', 'Week 1.2', 'Week 1.3', 'Week 1.4', 'Week 1.5',
       'Week 1.6', 'Week 1.7', 'Week 1.8', 'Week 2.1', 'Week 2.2', 'Week 2.3',
       'Week 2.4', 'Week 2.5', 'Week 2.6', 'Week 2.7', 'Week 2.8', 'Week 3.1',
       'Week 3.2', 'Week 3.3', 'Week 3.4', 'Week 3.5', 'Week 3.6', 'Week 3.7',
       'Week 3.8', 'Week 4.1', 'Week 4.2', 'Week 4.3', 'Week 4.4', 'Week 4.5',
       'Week 4.6', 'Week 4.7', 'Week 4.8', 'Week 5.1', 'Week 5.2', 'Week 5.3',
       'Week 5.4', 'Week 6.1', 'Week 6.2', 'Week 6.3', 'Week 6.4', 'Week 6.5',
       'Week 6.6', 'Week 6.7', 'Week 6.8', 'Week 7.1', 'Week 7.2', 'Week 7.3',
       'Week 7.4', 'Week 7.5', 'Week 7.6', 'Week 7.7', 'Week 7.8'],
      dtype='object')

In [439]:
#establishes new identifiers for table to begin creating multiple tables for refrence
col0 = df_2024.iloc[:, 0]
metric_names = ['Total Load', 'Total Sets', 'Total Reps', 'Weights Per Rep']
muscles = col0[~col0.isna() & ~col0.str.strip().isin(metric_names)].str.strip().tolist()

## Total Load

In [440]:
muscles = ["Chest","Shoulder", "Triceps", "Upper Back", "Traps", "Bicep", "Quads", "Hamstrings", "Calves"] #mucle groups
weeks = df_2024.columns[1:] #column 0 is for the year and weeks, so begining on column 1
C_total_load_table = pd.DataFrame(index=weeks, columns=muscles)
print(total_load_row.shape)

(40,)

In [442]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df_2024)
  muscle_block = df_2024.iloc[muscle_idx+1 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Total Load"
  C_total_load_row = muscle_block[mask].iloc[0, 1:]
  C_total_load_table[muscle] = C_total_load_row.values.flatten()

In [443]:
C_total_load_table.to_csv('C_total_load_table.csv', index=False)
from google.colab import files
files.download('C_total_load_table.csv')
print(C_total_load_table)

           Chest Shoulder Triceps Upper Back   Traps  Bicep   Quads  \
Week 1.1   5,030    1,320   3,780      5,750   2,400  1,680   3,960
Week 1.2   6,171    2,140   4,440      6,210   2,520  1,980   5,480
Week 1.3   6,856    2,370   4,392      6,820   3,000  2,420   6,520
Week 1.4   7,872    2,626   4,440      6,450   5,100  2,820   7,536
Week 1.5   8,540    2,980   5,232      8,350   5,700  3,200   8,568
Week 1.6   8,619    3,399   6,612     10,020   6,000  3,280   9,888
Week 1.7   9,502    3,390   6,160     15,130   2,640  3,200  12,670
Week 1.8   9,660    3,740   5,560     12,130   6,720      0       0
Week 2.1       0        0       0     14,500   2,800  3,056  11,510
Week 2.2   9,044    2,428     960      6,825   1,200  1,080  12,630
Week 2.3  10,385    3,760   4,580     13,410   5,600  3,190  16,505
Week 2.4  10,494    4,080   4,810     14,470   6,400  3,110  16,025
Week 2.5  11,904    4,760   6,936     18,260   7,200  4,280       0
Week 2.6  14,078    5,345   7,630     18,240   8,000  4,540  23,232
Week 2.7  13,233    5,085   8,340     16,680   8,040  3,840  24,312
Week 2.8       0        0       0     17,944   8,400  4,080  25,272
Week 3.1  11,222    4,320   6,470     14,080   6,480  3,240  25,416
Week 3.2  12,771    4,560   5,220     14,260   6,840  3,420  22,260
Week 3.3  13,127    5,530   6,812     16,080   7,020   3120  27,741
Week 3.4  12,345    5,475    5485     17,440   7,200  3,000  29,586
Week 3.5  14,005    7,425   5,700     20,970       0      0       0
Week 3.6  14,687    7,928   6,095      20035   8,400  3,920  18,945
Week 3.7  14,687    8,100    3060      20770   9,240  3,500       0
Week 3.8  15,215    7,560       0          0       0      0       0
Week 4.1  24,660    7,225   3,000     19,740   4,540  3,400  15,273
Week 4.2  21,708    7,490       0          0       0      0  19,553
Week 4.3  23,904    7,490   3,210     19,695   5,520  3,920  24,306
Week 4.4  24,865    8,440   2,620     19,970   2,940  3,352  26,690
Week 4.5  27,947    3,710   1,400      19708       0  1,900  26,238
Week 4.6  21,054    3,350   5,480     20,750       0  2,816       0
Week 4.7       0        0       0          0       0      0       0
Week 4.8       0        0       0          0       0      0       0
Week 5.1  10,894    3,248   1,350     11,760       0  1,350  21,494
Week 5.2  13,960    3,075   2,720     12,490       0  3,720  30,316
Week 5.3  15,288    3,560   3,560     15,720       0  3,554  32,193
Week 5.4  16,592    3,405   4,065     14,200   4,350  4,130  33,154
Week 6.1  13,585    3,405   2,940     13,550       0  2,710  16,407
Week 6.2  15,158    3,660   2,250     13,240       0  3,430  24,276
Week 6.3  16,801    4,265   3,800     12,840   2,940  3,630  27,797
Week 6.4  14,880    4,505   2,760     14,720   3,460  4,056  26,477
Week 6.5  15,157    5,220   3,860     13,867   3,830  4,072  28,367
Week 6.6  14,805    5,535   3,820     12,234   4,400  4,532  28,146
Week 6.7  15,139    5,815   4,280     14,094  11,730  4,032  26,494
Week 6.8  16,178    5,520   4,240     12,864  12,930  3,777  21,714
Week 7.1  15,494    5,295   2,080     13,696  14,920  4,432  15,864
Week 7.2  11,876    5,525   3,200     12,672  16,100  3,920  14,130
Week 7.3  14,274    1,775   1,680      5,790  16,590  4,848  13,875
Week 7.4  11,819    5,325   3,648     13,242  16,300  4,912  15,330
Week 7.5  13,075    4,740   3,275     13,265  16,630  4,520   4,815
Week 7.6  10,840    4,670   1,280     12,594       0  3,116   4,770
Week 7.7  15,430    4,635   3,240     10,166  16,410  4,221  13,140
Week 7.8  13,962    6,975   2,700      9,575  16,100  4,368  16,170

         Hamstrings  Calves
Week 1.1      2,640  17,340
Week 1.2      3,300  24,315
Week 1.3      4,350  26,475
Week 1.4      5,100  32,445
Week 1.5      6,112  55,386
Week 1.6      6,640  61,398
Week 1.7      7,040  67,880
Week 1.8          0       0
Week 2.1      4,520  22,806
Week 2.2      5,220  23,925
Week 2.3      5,880  46,980
Week 2.4      6,600  49,104
Week 2.5          0       0
Week 2.6      8,350  48,465
Week 2.7      8,600  50,374
Week 2.8      9,500  56,214
Week 3.1      5,600  53,109
Week 3.2      5,900  53,379
Week 3.3      7,250  58,044
Week 3.4      6,600  59,354
Week 3.5          0       0
Week 3.6      9,480  41,970
Week 3.7          0       0
Week 3.8          0       0
Week 4.1      7,510  12,047
Week 4.2      9,840  18,967
Week 4.3     10,440  19,800
Week 4.4          0       0
Week 4.5     11,040  27,664
Week 4.6          0       0
Week 4.7          0       0
Week 4.8          0       0
Week 5.1     10,510  20,841
Week 5.2     12,265  23,310
Week 5.3     13,220  27,000
Week 5.4     15,170  30,000
Week 6.1      6,240       0
Week 6.2     11,090  17,550
Week 6.3     11,550  33,657
Week 6.4     14,005  36,482
Week 6.5     14,295  41,649
Week 6.6     16,825  45,098
Week 6.7     17,553  53,250
Week 6.8     17,900  53,325
Week 7.1      7,260  29,025
Week 7.2     18,720  33,765
Week 7.3     19,575  35,460
Week 7.4     19,610  37,920
Week 7.5      7,820  24,360
Week 7.6     16,530   7,800
Week 7.7     11,530  38,100
Week 7.8     16,820  46,860

## Total Sets

In [444]:
muscles = ["Chest","Shoulder", "Triceps", "Upper Back", "Traps", "Bicep", "Quads", "Hamstrings", "Calves"] #mucle groups
weeks = df_2024.columns[1:] #column 0 is for the year and weeks, so begining on column 1
C_total_sets_table = pd.DataFrame(index=weeks, columns=muscles)
print(C_total_sets_row.shape)

(52,)

In [445]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df_2024)
  muscle_block = df_2024.iloc[muscle_idx+2 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Total Sets"
  C_total_sets_row = muscle_block[mask].iloc[0, 1:]
  C_total_sets_table[muscle] = C_total_sets_row.values.flatten()

In [447]:
C_total_sets_table.to_csv('C_total_sets_table.csv', index=False)
from google.colab import files
files.download('C_total_sets_table.csv')
print(C_total_sets_table)

         Chest Shoulder Triceps Upper Back Traps Bicep Quads Hamstrings Calves
Week 1.1     9        7       6         10     4     7     9          6      9
Week 1.2    11        9       6         13     3     7     9          6     12
Week 1.3    10        9       6         12     3     8     9          6     12
Week 1.4    10        9       6         10     5     8     9          6     12
Week 1.5    12       12       8         15     5     9    12          8     15
Week 1.6    13       12       9         16     5     9    12          8     15
Week 1.7    12       11       8         17     3     9    12          8     15
Week 1.8    13       11       8         14     6     0     0          0      0
Week 2.1     0        0       0         15     3     8     9          5      9
Week 2.2    11        9       6          9     3     3     9          6      9
Week 2.3    12       13       7         14     4     8    12          6     12
Week 2.4    12       13       8         15     4     9    11          6     12
Week 2.5    15       14      10         21     5    13     0          0      0
Week 2.6    18       15      12         22     5    14    11          9     12
Week 2.7    16       16      12         20     5    13    12          9     12
Week 2.8     0        0       0         20     5    13    12          9     12
Week 3.1    12        9       7         13     3     9     9          6     12
Week 3.2    12        9       7         13     3     9     9          6     12
Week 3.3    12        9       7         13     3     7     9          6     12
Week 3.4    12        9       7         13     3     6     9          6     12
Week 3.5    16       12       9         18     0     0     0          0      0
Week 3.6    17       13       9         18     4     8    12          9     11
Week 3.7    16       12       6         18     4     6     0          0      0
Week 3.8    16       12       0          0     0     0     0          0      0
Week 4.1    23       12       7         19     4     9    10          7      7
Week 4.2    18       14       0          0     0     0    15          9     10
Week 4.3    17       14       8         20     5     9    15          9     10
Week 4.4    20       14       8         21     3     9    16          0      0
Week 4.5    18       10       4         20     0     4    13         12     11
Week 4.6    20        8       8         21     0     8     0          0      0
Week 4.7     0        0       0          0     0     0     0          0      0
Week 4.8     0        0       0          0     0     0     0          0      0
Week 5.1    15        8       3         15     0     3    14         10     12
Week 5.2    17        8       7         15     0     7    17         14     13
Week 5.3    17        8       7         16     0     7    16         14     12
Week 5.4    17        8       7         15     0     7    10          6     12
Week 6.1    14        8       7         15     0     7     8          8      0
Week 6.2    18        8       7         15     0     7    16         16      5
Week 6.3    19        9       7         15     3     7    17         14     12
Week 6.4    15       10       6         15     3     6    15          8     12
Week 6.5    15       11       7         16     3     7    15         16     12
Week 6.6    15       12       8         15     3     8    16         16     12
Week 6.7    14       11       8         17     3     7    15         16     12
Week 6.8    15       11       8         17     3     7    16         16     12
Week 7.1    15       11       8         16     3     8     9          8      5
Week 7.2    15       11      10         16     3     9    11         17      8
Week 7.3    14        4       5          8     3     9    11         17      8
Week 7.4    14       11      10         16     3     9    11         17      8
Week 7.5    14        9      10         16     3     9     5          7      4
Week 7.6    14       11       5         15     0     5     5         13      3
Week 7.7    14       11      10         12     3     9    12         12      4
Week 7.8    15       11       9         12     3     9    14         17      8

## Total Reps

In [452]:
muscles = ["Chest","Shoulder", "Triceps", "Upper Back", "Traps", "Bicep", "Quads", "Hamstrings", "Calves"] #mucle groups
weeks = df_2024.columns[1:] #column 0 is for the year and weeks, so begining on column 1
C_total_reps_table = pd.DataFrame(index=weeks, columns=muscles)
print(C_total_reps_row.shape)

(52,)

In [456]:
for i, muscle in enumerate(muscles):
  muscle_rows = col0[col0.str.strip()== muscle]
  if len(muscle_rows) == 0:
      continue
  muscle_idx = muscle_rows.index[0]
  if i < len(muscles) - 1:
    next_muscle_idx = col0[col0.str.strip() == muscles[i + 1]].index[0]
  else:
    next_muscle_idx = len(df_2024)
  muscle_block = df_2024.iloc[muscle_idx+3 : next_muscle_idx, :]
  mask = muscle_block.iloc[:,0].str.strip() == "Total Reps"
  C_total_reps_row = muscle_block[mask].iloc[0, 1:]
  C_total_reps_table[muscle] = C_total_reps_row.values.flatten()

In [455]:
C_total_reps_table.to_csv('C_total_reps_table.csv', index=False)
from google.colab import files
files.download('C_total_reps_table.csv')
print(C_total_reps_table)

         Chest Shoulder Triceps Upper Back Traps Bicep Quads Hamstrings Calves
Week 1.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.5   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.6   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.7   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 1.8   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.5   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.6   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.7   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 2.8   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.5   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.6   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.7   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 3.8   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.5   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.6   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.7   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 4.8   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 5.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 5.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 5.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 5.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.5   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.6   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.7   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 6.8   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.1   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.2   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.3   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.4   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.5   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.6   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.7   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN
Week 7.8   NaN      NaN     NaN        NaN   NaN   NaN   NaN        NaN    NaN

## Weights Per Rep