# Organizing 2022-2023

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('2022-2023.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 41 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   55 non-null     object
 1   First        51 non-null     object
 2   Unnamed: 2   53 non-null     object
 3   Unnamed: 3   51 non-null     object
 4   Unnamed: 4   47 non-null     object
 5   Unnamed: 5   47 non-null     object
 6   Unnamed: 6   9 non-null      object
 7   Unnamed: 7   9 non-null      object
 8   Unnamed: 8   9 non-null      object
 9   Second       47 non-null     object
 10  Unnamed: 10  51 non-null     object
 11  Unnamed: 11  53 non-null     object
 12  Unnamed: 12  53 non-null     object
 13  Unnamed: 13  47 non-null     object
 14  Unnamed: 14  47 non-null     object
 15  Unnamed: 15  42 non-null     object
 16  Unnamed: 16  47 non-null     object
 17  Third        42 non-null     object
 18  Unnamed: 18  53 non-null     object
 19  Unnamed: 19  55 non-null     object
 20  Unnamed: 20  49 non-null     object
 21  Unnamed: 21  43 non-null     object
 22  Unnamed: 22  9 non-null      object
 23  Unnamed: 23  9 non-null      object
 24  Unnamed: 24  9 non-null      object
 25  Fourth       51 non-null     object
 26  Unnamed: 26  42 non-null     object
 27  Unnamed: 27  55 non-null     object
 28  Unnamed: 28  51 non-null     object
 29  Unnamed: 29  49 non-null     object
 30  Unnamed: 30  45 non-null     object
 31  Unnamed: 31  51 non-null     object
 32  Unnamed: 32  55 non-null     object
 33  Fifth        55 non-null     object
 34  Unnamed: 34  45 non-null     object
 35  Unnamed: 35  55 non-null     object
 36  Unnamed: 36  45 non-null     object
 37  Unnamed: 37  49 non-null     object
 38  Unnamed: 38  55 non-null     object
 39  Unnamed: 39  9 non-null      object
 40  Unnamed: 40  9 non-null      object
dtypes: object(41)
memory usage: 20.9+ KB

,Unnamed: 0,First,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second,...,Unnamed: 31,Unnamed: 32,Fifth,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
count,55,51,53,51,47,47,9,9,9,47,...,51,55,55,45,55,45,49,55,9,9
unique,15,30,41,38,26,26,1,1,1,27,...,36,44,45,22,39,21,31,44,1,1
top,Total Load,Week 1,Week 2,Week 3,0,0,Week 6,Week 7,Week 8,0,...,Week 7,Week 8,Week 1,0,Week 3,0,Week 5,Week 6,Week 7,Week 8
freq,9,9,9,9,12,12,9,9,9,12,...,9,9,9,15,9,15,9,9,9,9

In [ ]:
df.head()

,Unnamed: 0,First,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second,...,Unnamed: 31,Unnamed: 32,Fifth,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,Chest,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,Total Load,0,"8,690","6,085","2,360","7,300",NaN,NaN,NaN,"7,915",...,"10,520","12,434","12,075",0,"15,804","13,600",0,"16,595",NaN,NaN
2,Total Sets,0,15,14,8,13,NaN,NaN,NaN,12,...,19,21,23,0,24,20,0,27,NaN,NaN
3,Total Reps,0,141,136,88,129,NaN,NaN,NaN,125,...,235,237,259,0,264,255,0,373,NaN,NaN
4,Weights Per Rep,NaN,62,45,27,57,NaN,NaN,NaN,63,...,45,52,47,NaN,60,53,NaN,44,NaN,NaN

In [ ]:
df.shape

(65, 41)

In [ ]:
list(df.columns) #identifying columns needed for renaming

['Unnamed: 0',
 'First',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Second',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Third',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Fourth',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Fifth',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40']

In [ ]:
df.iloc[:, 1:41]

,First,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Second,Unnamed: 10,...,Unnamed: 31,Unnamed: 32,Fifth,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,Week 2,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,0,"8,690","6,085","2,360","7,300",NaN,NaN,NaN,"7,915","10,441",...,"10,520","12,434","12,075",0,"15,804","13,600",0,"16,595",NaN,NaN
2,0,15,14,8,13,NaN,NaN,NaN,12,13,...,19,21,23,0,24,20,0,27,NaN,NaN
3,0,141,136,88,129,NaN,NaN,NaN,125,121,...,235,237,259,0,264,255,0,373,NaN,NaN
4,NaN,62,45,27,57,NaN,NaN,NaN,63,86,...,45,52,47,NaN,60,53,NaN,44,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,148,99,50,NaN,NaN,NaN,NaN,NaN,120,140,...,NaN,157,207,NaN,207,NaN,NaN,108,NaN,NaN
61,0%,-49%,-98%,NaN,NaN,NaN,NaN,NaN,58%,14%,...,NaN,3%,24%,NaN,0%,NaN,NaN,-92%,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,June 28-July 1,July 5-9,July 18-21,July 25-26,Aug 8-9,NaN,NaN,NaN,Oct 13-14,Oct 17-21,...,July 3-8,July 10-14,July 17-21,July 24-25,July 31-Aug 4,Aug 7-11,Aug 14-18,Aug 21-26,NaN,NaN

In [ ]:
#Changing the Columns to better identify weeks and sections(Week 1.1 is First Grouping First Week)
df1 = df.rename(columns={'Unnamed: 0': "2022-2023",
 'First': "Week 1.1",
 'Unnamed: 2': "Week 1.2",
 'Unnamed: 3': "Week 1.3",
 'Unnamed: 4': "Week 1.4",
 'Unnamed: 5': "Week 1.5",
 'Unnamed: 6': "Week 1.6",
 'Unnamed: 7': "Week 1.7",
 'Unnamed: 8': "Week 1.8",
 'Second': "Week 2.1",
 'Unnamed: 10': "Week 2.2",
 'Unnamed: 11': "Week 2.3",
 'Unnamed: 12': "Week 2.4",
 'Unnamed: 13': "Week 2.5",
 'Unnamed: 14': "Week 2.6",
 'Unnamed: 15': "Week 2.7",
 'Unnamed: 16': "Week 2.8",
 'Third': "Week 3.1",
 'Unnamed: 18': "Week 3.2",
 'Unnamed: 19': "Week 3.3",
 'Unnamed: 20': "Week 3.4",
 'Unnamed: 21': "Week 3.5",
 'Unnamed: 22': "Week 3.6",
 'Unnamed: 23': "Week 3.7",
 'Unnamed: 24': "Week 3.8",
 'Fourth': "Week 4.1",
 'Unnamed: 26': "Week 4.2",
 'Unnamed: 27': "Week 4.3",
 'Unnamed: 28': "Week 4.4",
 'Unnamed: 29': "Week 4.5",
 'Unnamed: 30': "Week 4.6",
 'Unnamed: 31': "Week 4.7",
 'Unnamed: 32': "Week 4.8",
 'Fifth': "Week 5.1",
 'Unnamed: 34': "Week 5.2",
 'Unnamed: 35': "Week 5.3",
 'Unnamed: 36': "Week 5.4",
 'Unnamed: 37': "Week 5.5",
 'Unnamed: 38': "Week 5.6",
 'Unnamed: 39': "Week 5.7",
 'Unnamed: 40': "Week 5.8" }, inplace=True)

In [ ]:
print(df.columns) #verification of rename

Index(['2022-2023', 'Week 1.1', 'Week 1.2', 'Week 1.3', 'Week 1.4', 'Week 1.5',
       'Week 1.6', 'Week 1.7', 'Week 1.8', 'Week 2.1', 'Week 2.2', 'Week 2.3',
       'Week 2.4', 'Week 2.5', 'Week 2.6', 'Week 2.7', 'Week 2.8', 'Week 3.1',
       'Week 3.2', 'Week 3.3', 'Week 3.4', 'Week 3.5', 'Week 3.6', 'Week 3.7',
       'Week 3.8', 'Week 4.1', 'Week 4.2', 'Week 4.3', 'Week 4.4', 'Week 4.5',
       'Week 4.6', 'Week 4.7', 'Week 4.8', 'Week 5.1', 'Week 5.2', 'Week 5.3',
       'Week 5.4', 'Week 5.5', 'Week 5.6', 'Week 5.7', 'Week 5.8'],
      dtype='object')

In [ ]:
#establishes new identifiers for table to begin creating multiple tables for refrence
col0 = df.iloc[:, 0]
metric_names = ['Total Load', 'Total Sets', 'Total Reps', 'Weights Per Rep']
muscles = col0[~col0.isna() & ~col0.str.strip().isin(metric_names)].str.strip().tolist()

In [ ]:
#begin total load table
muscles = ["Chest","Shoulders", "Triceps", "Upper Back", "Traps", "Biceps", "Quads", "Hamstrings", "Calves"] #mucle groups
weeks = df.columns[1:] #column 0 is for the year and weeks, so begining on column 1
total_load_table = pd.DataFrame(index=weeks, columns=muscles)

In [ ]:
for muscle in muscles:
    muscle_idx = df.index[df.iloc[:, 0] == muscle][0]
    muscle_rows = col0[col0.str.strip()== muscle]
    if len(muscle_rows) == 0:
      continue
    total_load_row = df.iloc[muscle_idx + 1, 1:]
    total_load_table[muscle] = total_load_row.values

In [ ]:
#from google.colab import files
#files.download('total_load_table.csv')

In [ ]:
#verification of new table total load and beggining of cleaning of data
df = pd.read_csv('total_load_table.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  40 non-null     object
 1   Chest       31 non-null     object
 2   Shoulders   32 non-null     object
 3   Triceps     32 non-null     object
 4   Upper Back  32 non-null     object
 5   Traps       32 non-null     object
 6   Biceps      32 non-null     object
 7   Quads       32 non-null     object
 8   Hamstrings  32 non-null     object
 9   Calves      32 non-null     object
dtypes: object(10)
memory usage: 3.3+ KB

,Unnamed: 0,Chest,Shoulders,Triceps,Upper Back,Traps,Biceps,Quads,Hamstrings,Calves
count,40,31,32,32,32,32,32,32,32,32
unique,40,28,24,23,25,11,25,27,24,16
top,Week 1.1,0,0,0,0,0,0,0,0,0
freq,1,4,9,8,8,21,7,6,9,14

In [ ]:
df.fillna(0) #fillna 0 is more relevant due to the empty spots being times were a workout was not initiatiated
#Reminder: Eliminate Row 0 begining at column 1

,2022-2023,Week 1.1,Week 1.2,Week 1.3,Week 1.4,Week 1.5,Week 1.6,Week 1.7,Week 1.8,Week 2.1,...,Week 4.7,Week 4.8,Week 5.1,Week 5.2,Week 5.3,Week 5.4,Week 5.5,Week 5.6,Week 5.7,Week 5.8
0,Chest,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 1,...,Week 7,Week 8,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8
1,Total Load,0,"8,690","6,085","2,360","7,300",0,0,0,"7,915",...,"10,520","12,434","12,075",0,"15,804","13,600",0,"16,595",0,0
2,Total Sets,0,15,14,8,13,0,0,0,12,...,19,21,23,0,24,20,0,27,0,0
3,Total Reps,0,141,136,88,129,0,0,0,125,...,235,237,259,0,264,255,0,373,0,0
4,Weights Per Rep,0,62,45,27,57,0,0,0,63,...,45,52,47,0,60,53,0,44,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Weights Per Rep,148,99,50,0,0,0,0,0,120,...,0,157,207,0,207,0,0,108,0,0
61,Percentage Change,0%,-49%,-98%,0,0,0,0,0,58%,...,0,3%,24%,0,0%,0,0,-92%,0,0
62,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64,Dates:,June 28-July 1,July 5-9,July 18-21,July 25-26,Aug 8-9,0,0,0,Oct 13-14,...,July 3-8,July 10-14,July 17-21,July 24-25,July 31-Aug 4,Aug 7-11,Aug 14-18,Aug 21-26,0,0

Total Reps

In [1]:
#begining of Total Reps Table, mirroring total load table until automation/indexing is complete
col0 = df.iloc[:, 0]
metric_names = ['Total Load', 'Total Sets', 'Total Reps', 'Weights Per Rep']
muscles = col0[~col0.isna() & ~col0.str.strip().isin(metric_names)].str.strip().tolist()

NameError: name 'df' is not defined

In [ ]:
muscles = ["Chest","Shoulders", "Triceps", "Upper Back", "Traps", "Biceps", "Quads", "Hamstrings", "Calves"]
weeks = df.columns[1:]
total_rep_table = pd.DataFrame(index=weeks, columns=muscles)

# Organizing 2024-2025